name: Build and Deploy
on: [push]
jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Environment
        run: |
          echo "Runner OS: Windows (self-hosted)"
          echo "Docker version: $(docker --version)"
          echo "kubectl client version: $(kubectl version --client --output=json | ConvertFrom-Json).clientVersion.gitVersion"

      - name: Validate Secrets Exist
        run: |
          if (-not "${{ secrets.DOCKER_USERNAME }}") { 
            Write-Error "DOCKER_USERNAME secret is empty!"
            exit 1
          }
          echo "DOCKER_USERNAME secret exists (value hidden)"
          echo "DOCKER_PASSWORD secret exists (value hidden)"

      - name: Clean Docker Config
        run: |
          Remove-Item -Path ~/.docker/config.json -ErrorAction SilentlyContinue
          echo "Cleared existing Docker credentials"

      - name: Log in to Docker Hub
        run: |
          $password = "${{ secrets.DOCKER_PASSWORD }}"
          $password = $password -replace '([!$])', '`$1'  # Escape special chars
          $loginOutput = $(echo "${password}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" docker.io --password-stdin 2>&1)
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Docker login failed: $loginOutput"
              exit 1
          }
          echo "Docker login succeeded"

      - name: Build and Push Docker Image
        run: |
          docker build -t faizz209/my-app:latest .
          docker push faizz209/my-app:latest
          echo "Image successfully pushed to Docker Hub"

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          echo "Deployment status:"
          kubectl get deployments,services,pods
          echo "Minikube service URL:"
          minikube service my-app-service --url